item { 
	name:'n1'
	id:1
}
item { 
	name:'n2'
	id:2
}
item { 
	name:'n3'
	id:3
}
item { 
	name:'n4'
	id:4
}
item { 
	name:'n5'
	id:5
}
item { 
	name:'n6'
	id:6
}
item { 
	name:'n7'
	id:7
}
item { 
	name:'n8'
	id:8
}
item { 
	name:'n9'
	id:9
}
item { 
	name:'n0'
	id:10
}
item { 
	name:'Char'
	id:11
}
item { 
	name:'vReg'
	id:12
}
item { 
	name:'hReg'
	id:13
}
item { 
	name:'oReg'
	id:14
}
